pipeline
{
    agent any
    tools {
        maven ' maven '
        }
    stages
    {
        stage ( ' Build ' )
            steps
            {
            }
            post
                 git ' https://github.com/simpleit/test-jenkins-integration/ '
                 sh " mvn -Dmaven . test . failure . ignore = true clean package "
            }
                success
                    junit '** / target / surefire - reports / TEST - * . xml '
                    archiveArtifacts ' target / * . jar '
        stage ( " Deploy to QA " ) {
            steps {
                echo ( " deploy to qa " )
            }
        }

        stage ( ' Regression Automation Test ' ) {
            steps {
                catchError ( buildResult : ' SUCCESS ' , stageResult : ' FAILURE ' ) {
                    git 'https://github.com/Darkkenral/testJenkinsPlaywhrite.git'
                    sh " mvn clean test -Dsurefire.suiteXmlFiles - src / test / resources / test runners / testng_regressions.xml "
  
                }
            }
        }
        stage ( ' Publish Extent Report ' ) {
            steps { publishHTML ( [ allowMissing:false,
                            alwaysLinkToLastBuild : false ,
                            keepAll : true ,
                            reportDir : ' build ' ,
                            reportFiles : ' TestExecutionReport.html ' ,
                            reportName : ' HTML Extent Report ' ,
                            reportTitles : ''] )
            }
         }


}