pipeline
{
    agent any

    stages {
        stage('Build'){
            steps
            {
            git 'https://github.com/simpleit/test-jenkins-integration/ '
            echo("Descargando git")
            }
        
        }    
        stage("Deploy to QA"){
            steps{
                echo("deploy to qa")
            }
        }

        stage('Regression Automation Test '){
            steps {
                 echo("Regression Automation Test ")
                }
            }
        
        stage(' Publish Extent Report ') {
            steps {
                echo("Publish Extent Report")
            }
        }
    }

}